export const FETCH_MEALS_BEGIN   = 'FETCH_MEALS_BEGIN';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
export const FETCH_MEALS_FAILURE = 'FETCH_MEALS_FAILURE';

export const FETCH_MEAL_BEGIN   = 'FETCH_MEAL_BEGIN';
export const FETCH_MEAL_SUCCESS = 'FETCH_MEAL_SUCCESS';
export const FETCH_MEAL_FAILURE = 'FETCH_MEAL_FAILURE';


export const FETCH_MENU_BEGIN   = 'FETCH_MENU_BEGIN';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE';
export const REMOVE_CART = 'REMOVE_CART';

export const FETCH_USER_ORDERS_BEGIN   = 'FETCH_USER_ORDERS_BEGIN';
export const FETCH_USER_ORDERS_SUCCESS = 'FETCH_USER_ORDERS_SUCCESS';
export const FETCH_USER_ORDERS_FAILURE = 'FETCH_USER_ORDERS_FAILURE';
